<?
$campos = "avaliacaoquestionariointerno.db170_sequencial,avaliacaoquestionariointerno.db170_avaliacao,avaliacaoquestionariointerno.db170_transmitido,avaliacaoquestionariointerno.db170_ativo,avaliacaoquestionariointerno.db170_codigo";
?>
